[ELY-1850] CredentialStore API missing ability to check alias types
wildfly-security/wildfly-elytron pull request #1602
Opened 2021-10-15 08:33 UTC by lvydra

https://issues.redhat.com/browse/ELY-1850

2021-10-15 13:01 UTC, Skyllarr commented
@lvydra Thank you for PR! Can you please add a test for this as well?

2021-11-05 16:18 UTC, fjuma requested changes
Thanks @lvydra! Just have some small comments.

2021-11-05 16:18 UTC, fjuma commented on credential/store/src/main/java/org/wildfly/security/credential/store/CredentialStore.java
> +    public Set<String> getStoredTypesForAlias(String credentialAlias) throws UnsupportedOperationException {
Just a small comment, to be consistent with the parameter name used when removing a credential, perhaps we could rename this method to `getCredentialTypesForAlias`.

2021-11-05 16:18 UTC, fjuma commented on credential/store/src/main/java/org/wildfly/security/credential/store/CredentialStoreSpi.java
> +    public Set<String> getStoredTypesForAlias(String credentialAlias) throws UnsupportedOperationException {
Same here.

2021-11-05 16:18 UTC, fjuma commented on tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
> +    public static final String STORED_TYPES = "stored-types";
`CREDENTIAL_TYPES="credential-types"`

2021-11-05 16:18 UTC, fjuma commented on tool/src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
> +    private void aliasStoredTypes(CredentialStore credentialStore) {
Same here.

2021-11-08 10:21 UTC, lvydra commented
@fjuma Thanks, fixed.

2021-11-08 16:15 UTC, fjuma approved these changes
Thanks @lvydra!

2021-11-08 16:15 UTC, merged