[ELY-2625] Add a test to X500AttributePrincipalDecoderTest that makes…
wildfly-security/wildfly-elytron pull request #1988
Opened 2023-10-02 18:26 UTC by gerjantd

… use of the PrincipalDecoder#aggregate method

2023-10-06 18:07 UTC, PrarthonaPaul requested changes

2023-10-06 18:07 UTC, PrarthonaPaul commented on tests/base/src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java
> +        dcDecoder = new X500AttributePrincipalDecoder(X500.OID_DC);
Thank you for the PR! 
This is very minor, instead of declaring the variables and the assigning them separately, would it be better to declare and assign in the same line? And when they are reassigned, you can just keep it as is. 
So, something like 
```
X500Principal principal = new X500Principal("cn=bob.smith,cn=bob,ou=people,dc=example,dc=redhat,dc=com");
```
and so on.

2023-10-06 18:46 UTC, gerjantd commented on tests/base/src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java
> +        dcDecoder = new X500AttributePrincipalDecoder(X500.OID_DC);
Ack will do that.
My reasoning was that it seemed a little clearer having the assignments on separate lines as these vars get re-assigned a few times. But there is value in fewer lines too.
I will fix it and push.

2023-10-06 19:18 UTC, gerjantd commented on tests/base/src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java
> +        dcDecoder = new X500AttributePrincipalDecoder(X500.OID_DC);
Squashed & pushed.

2023-10-06 19:22 UTC, PrarthonaPaul commented on tests/base/src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java
> +        dcDecoder = new X500AttributePrincipalDecoder(X500.OID_DC);
Thanks! 
Once the CI runs, it should be good to go!

2023-10-07 04:05 UTC, gerjantd commented on tests/base/src/test/java/org/wildfly/security/x500/X500AttributePrincipalDecoderTest.java
> +        dcDecoder = new X500AttributePrincipalDecoder(X500.OID_DC);
The Jira links here. Let me know if it is OK please. Thanks!

2023-10-10 13:19 UTC, PrarthonaPaul approved these changes
LGTM Thanks @gerjantd

2023-10-12 15:46 UTC, Skyllarr approved these changes

2023-10-13 19:49 UTC, fjuma approved these changes
Thanks @gerjantd!

2023-10-13 19:49 UTC, merged