[ELY-2685] Replace assert in PasswordBasedEncryptionUtilTest with a p…
wildfly-security/wildfly-elytron pull request #2009
Opened 2023-10-13 18:54 UTC by ericrleung

…roper check
https://issues.redhat.com/browse/ELY-2685

2023-10-13 19:38 UTC, PrarthonaPaul requested changes

2023-10-13 19:38 UTC, PrarthonaPaul commented on tests/base/src/test/java/org/wildfly/security/util/PasswordBasedEncryptionUtilTest.java
> +        Assert.assertEquals("Elytron in PB compatible mode failed", decrypted, secret);
Thank you @ericrleung for the PR! 
Very minor, but could you please change the order of the values so it is following the format assertTrue( message, expectedValue, actualValue) ? Thank you! Here, I believe `secret` and `encrypted` are the expected values.

2023-10-16 13:47 UTC, fjuma approved these changes
Thanks @ericrleung!

2023-10-16 18:42 UTC, PrarthonaPaul approved these changes
LGTM!

2023-10-17 08:44 UTC, Skyllarr approved these changes

2023-10-17 08:44 UTC, merged