[ELY-2686] Merge an if statement with the enclosing one in X509EvidenceVerifier
wildfly-security/wildfly-elytron pull request #2011
Opened 2023-10-13 19:34 UTC by VAIBHAVCES

[ELY-2686]Merge an if statement with the enclosing one in X509EvidenceVerifier
Jira : https://issues.redhat.com/browse/ELY-2686

2023-10-13 19:52 UTC, PrarthonaPaul commented
Hi @VAIBHAVCES 
Thanks for the PR!
Could you please edit the commit message and the PR description to match the Jira issue and add the link to the Jira here?

2023-10-13 19:54 UTC, VAIBHAVCES commented
> Hi @VAIBHAVCES Thanks for the PR! Could you please edit the commit message and the PR description to match the Jira issue and add the link to the Jira here?

@PrarthonaPaul I see  jira issue is already updated the in commit, description and summary.
What else I need to update ?

2023-10-13 19:57 UTC, fjuma commented on auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
> +                    return attrCertificate != null
We need to be a bit careful here. We still need an if statement to make sure we only return true if `attrCertificate != null` and `MessageDigest.isEqual(certificate.getEncoded(), (byte[]) attrCertificate)` are both `true`. If not, the current changes return `false` but that's different from the current behaviour.

2023-10-13 19:58 UTC, fjuma requested changes
Added a small comment.

2023-10-13 20:02 UTC, VAIBHAVCES commented on auth/realm/ldap/src/main/java/org/wildfly/security/auth/realm/ldap/X509EvidenceVerifier.java
> +                    return attrCertificate != null
sure reverted @fjuma  please review now

2023-10-13 20:09 UTC, PrarthonaPaul commented
> > Hi @VAIBHAVCES Thanks for the PR! Could you please edit the commit message and the PR description to match the Jira issue and add the link to the Jira here?
> 
> @PrarthonaPaul I see jira issue is already updated the in commit, description and summary. What else I need to update ?

Oh, sorry. 
I was referring to the Jira link and updating the commit message to `Merge an if statement with the enclosing one in X509EvidenceVerifier` as opposed to `Removed multiples if and made it single liner`
You can use `git commit --ammend` to do this.

2023-10-13 20:13 UTC, VAIBHAVCES commented
> Added a small comment.



> > > Hi @VAIBHAVCES Thanks for the PR! Could you please edit the commit message and the PR description to match the Jira issue and add the link to the Jira here?
> > 
> > 
> > @PrarthonaPaul I see jira issue is already updated the in commit, description and summary. What else I need to update ?
> 
> Oh, sorry. I was referring to the Jira link and updating the commit message to `Merge an if statement with the enclosing one in X509EvidenceVerifier` as opposed to `Removed multiples if and made it single liner` You can use `git commit --ammend` to do this.

done

2023-10-16 13:06 UTC, PrarthonaPaul approved these changes
LGTM!

2023-10-16 13:46 UTC, fjuma approved these changes
Thanks @VAIBHAVCES!

2023-10-16 14:16 UTC, Skyllarr approved these changes

2023-10-16 14:16 UTC, merged