[ELY-2684] Unit test code refactor (removed duplicates)
wildfly-security/wildfly-elytron pull request #2041
Opened 2023-10-22 17:29 UTC by sugan0tech

https://issues.redhat.com/browse/ELY-2684

2023-10-23 18:58 UTC, fjuma requested changes
Looks good, @sugan0tech, I've just added a small comment.

For the title and commit message, it would be good to include information about the specific test that was updated, e.g., [ELY-2648] Update tests in OTPTest to use a common helper method for tests where the password should remain unchanged"

2023-10-23 18:58 UTC, fjuma commented on tests/base/src/test/java/org/wildfly/security/sasl/otp/OTPTest.java
> +    private void testAuthentication(String seed, int sequenceNumber) throws Exception {
Would be good to rename this to explain what it does, e.g., checkPasswordRemainsUnchanged or testPasswordRemainsUnchanged, etc.

2023-10-23 19:01 UTC, sugan0tech commented on tests/base/src/test/java/org/wildfly/security/sasl/otp/OTPTest.java
> +    private void testAuthentication(String seed, int sequenceNumber) throws Exception {
Sure :+1:

2023-10-25 19:53 UTC, fjuma approved these changes
Thanks very much @sugan0tech!

2023-10-25 20:12 UTC, PrarthonaPaul approved these changes
LGTM! 
Thanks @sugan0tech

2023-10-26 14:18 UTC, Skyllarr approved these changes

2023-10-26 14:18 UTC, merged