[ELY-2693] Unit test code refactor (removed duplicates)
wildfly-security/wildfly-elytron pull request #2042
Opened 2023-10-22 18:10 UTC by sugan0tech

https://issues.redhat.com/browse/ELY-2693

2023-10-23 19:01 UTC, fjuma requested changes
Thanks @sugan0tech, this looks good, I've only added a small comment.

If you could also update the title and commit message to add details about the specific test class that is being updated (similar to my comment in the other PR), that would also be good.

Thanks!

2023-10-23 19:01 UTC, fjuma commented on tests/base/src/test/java/org/wildfly/security/auth/realm/token/JwtSecurityRealmTest.java
> +    private void testTokenSecurityRealm(String kid, int port) throws Exception {
Would be good to rename this to explain what the method does, e.g., checkIdentityDoesNotExist or testIdentityDoesNotExist, etc.

2023-10-25 19:54 UTC, fjuma approved these changes
Thanks very much @sugan0tech!

2023-10-26 14:08 UTC, Skyllarr approved these changes

2023-10-26 14:09 UTC, merged