[ELY-2547] Add Elytron Tool option to overwrite CLI script
wildfly-security/wildfly-elytron pull request #2194
Opened 2024-09-18 09:26 UTC by lvydra

Re-apply the changes for https://issues.redhat.com/browse/ELY-2547

2024-09-18 13:03 UTC, lvydra commented
@darranl  Well, it seems that `FileSystemEncryptRealmCommandTes.testOverwritingScriptFileTrue` is intermittently failing. I will try to tweak it.

2024-09-19 16:05 UTC, darranl approved these changes

2024-09-19 17:41 UTC, fjuma commented
@lvydra Looks like this is still flaky on CI.

2024-09-20 12:54 UTC, lvydra commented
@fjuma @darranl Please rerun the tests to confirm if the changes are stable.

2024-09-20 14:31 UTC, darranl commented
Last run was green, running again for stability.

2024-09-20 19:07 UTC, fjuma commented
Last run was green, running again.

2024-09-20 19:08 UTC, fjuma commented
@lvydra Just so we can reference this later on if needed, would you be able to add a quick comment about the intermittent failure and how it was fixed?

2024-09-23 08:26 UTC, lvydra commented
Sure @fjuma . In 'FileSystemEncryptRealmCommandTest' I have been using 'File.lastModified()' method to check if the file has been modified, but as I have found out later this method does not always return the latest value on Windows probably due to the file attributes caching. 
So I switched to assertion based on file content.

2024-11-15 09:44 UTC, lvydra commented
Hi @fjuma, could you look at this one again, thanks.

2025-03-05 20:27 UTC, fjuma approved these changes

2025-03-06 21:36 UTC, rhusar requested changes

2025-03-06 21:36 UTC, rhusar commented on tool/src/test/resources/filesystem-integrity/fs-unsigned-realms/fsRealmAl/a/l/alice-MFWGSY3F.xml
> +    </identity>
You should run a formatter on this XML file ;-)

2025-03-07 07:09 UTC, lvydra commented on tool/src/test/resources/filesystem-integrity/fs-unsigned-realms/fsRealmAl/a/l/alice-MFWGSY3F.xml
> +    </identity>
Thanks @rhusar, updated.

2025-03-12 09:47 UTC, rhusar approved these changes
👍🏼 No more comments from me.

2025-04-02 16:06 UTC, ivassile commented
@fjuma This PR is ready and can be merged.

2025-04-13 13:51 UTC, darranl commented
@lvydra sorry but we still seem to have CI failures https://github.com/wildfly-security/wildfly-elytron/pull/2272

2025-04-13 14:08 UTC, darranl requested changes
See comments

2025-04-14 08:38 UTC, lvydra commented
Hi @darranl, thanks for looking at it. This change should help.

2025-07-30 13:12 UTC, Skyllarr approved these changes

2025-07-30 13:15 UTC, Skyllarr commented
> @lvydra sorry but we still seem to have CI failures #2272

@darranl You requested changes on this PR because the CI was failing (#2272). This  PR was updated and the CI now passes here. So you can  merge this one and close https://github.com/wildfly-security/wildfly-elytron/pull/2272

2025-09-13 15:53 UTC, merged