WFLY-18650 - Security roles lost following failover
wildfly-security/wildfly-elytron pull request #2247
Opened 2024-12-17 13:56 UTC by pedro-hos

- https://issues.redhat.com/browse/WFLY-18650
- https://issues.redhat.com/browse/JBEAP-28744

2025-01-15 15:34 UTC, fjuma commented
@pedro-hos Thanks for your PR! Just noticed that the PR is currently referencing a WFLY issue instead of an ELY issue. Please move the WFLY issue to the ELY project and update the PR title and commit to reference the ELY issue instead.

Please also submit this PR against the 2.6.x branch instead of the 2.x branch.

Thanks!

2025-01-27 17:28 UTC, pedro-hos commented
> @pedro-hos Thanks for your PR! Just noticed that the PR is currently referencing a WFLY issue instead of an ELY issue. Please move the WFLY issue to the ELY project and update the PR title and commit to reference the ELY issue instead.
> 
> Please also submit this PR against the 2.6.x branch instead of the 2.x branch.
> 
> Thanks!

@fjuma Thank you for your feedback. I think that this is ok now. I moved from 2.x to 2.6.x and created the new ELY issue

2025-06-12 15:08 UTC, darranl commented
@pedro-hos FYI this PR currently have a merge conflict, but also I think we are ready to look at where a test case can live for this scenario - the changes I made previously to Elytron Web may be possible to be extended to add this kind of scenario.

2025-07-10 08:05 UTC, Skyllarr requested changes
Just to note here that a PR with a test is here: https://github.com/wildfly-security/elytron-web/pull/285

2025-07-10 08:05 UTC, skyllarr commented on wildfly-elytron/pom.xml
> +                                    <version>2.6.4.Final</version> <!-- When updating to next release, clear all exclusions. -->
Hi @pedro-hos , this PR should not change the version here

2025-07-10 12:46 UTC, pedro-hos commented on wildfly-elytron/pom.xml
> +                                    <version>2.6.4.Final</version> <!-- When updating to next release, clear all exclusions. -->
Thank you @Skyllarr

2025-07-14 10:21 UTC, skyllarr commented
@pedro-hos I needed to rewrite a commit message here so it contains ELY issue number and add a fix on top of this. So I submitted https://github.com/wildfly-security/wildfly-elytron/pull/2294 that supersedes this PR

2025-07-14 13:23 UTC, pedro-hos commented
@Skyllarr May we close this one so?

2025-07-14 14:18 UTC, Skyllarr commented
Superseded by https://github.com/wildfly-security/wildfly-elytron/pull/2294

2025-07-30 13:16 UTC, Skyllarr commented
Superseded by https://github.com/wildfly-security/wildfly-elytron/pull/2294

2025-07-30 13:16 UTC, closed without merging